### ISSUE TITLE
Nested Components do not work currently with MergeComponent

### ISSUE THREAD

**Issue by chrisbanes** [r0adkll/kimchi#43]
We use [nested components](https://github.com/evant/kotlin-inject#component-inheritance) in Kotlin Inject, but unfortunately they don't seem to work correctly with `MergeComponent`. 

Here's an example which doesn't work right now:

``` kotlin
@ProfileScope
@MergeComponent(ProfileScope::class)
abstract class ProfileComponent(
    @get:Provides override val profileId: ProfileId,
    @Component val applicationComponent: ApplicationComponent,
)
```

The generated code is the following, which is missing the `val`:

``` kotlin
@ProfileScope
@Component
public abstract class MergedProfileComponent(
  profileId: ProfileId,
  @Component
  applicationComponent: ApplicationComponent,
) : ProfileComponent(profileId, applicationObjectGraph) {
  public companion object
}
```

The fix is pretty simple: keep the `val`

**Comment by r0adkll** [comment]
Oh good catch. I had not considered nested components when defining a `@MergeComponent`, but instead relied upon the `@MergeSubcomponent` mechanism. This should be an easy fix

**Comment by chrisbanes** [comment]
Oh interesting, I missed `@ MergeSubcomponent`. Maybe that's the better fix for us

**Comment by r0adkll** [comment]
Okay, this should be fixed now. Looks like kotlin-inject handles inheritance properly so we don't really need to duplicate the annotations on the generated merged component at all and can just let the underlying definition provide it.
