### ISSUE TITLE
MapKey is broken

### ISSUE THREAD

**Issue by kodebach** [r0adkll/kimchi#50]
The docs for `MapKey` contain an example

https://github.com/r0adkll/kimchi/blob/0db50f5f178900d1dc3bae2f86c88b5a698a8f82/annotations/src/commonMain/kotlin/com/r0adkll/kimchi/annotations/MapKey.kt#L11-L31

However, compiling a full example like

```kotlin
object TestScope

@MergeComponent(TestScope::class)
abstract class TestComponent

interface Injector
object FeatureScreen

@MapKey
annotation class ClassKey(val clazz: KClass<*>)

@ClassKey(FeatureScreen::class)
@ContributesMultibinding(TestScope::class)
@Inject
class FeatureInjector : Injector
```

actually produces broken output

```kotlin
@Component
public abstract class MergedTestComponent() : TestComponent() {
  @Provides
  @IntoMap
  public fun provideInjector_FeatureScreen(`value`: FeatureInjector): Pair<KSTypeImpl, Injector> =
      (FeatureScreen to value)

  public companion object
}

public fun KClass<TestComponent>.createTestComponent(): MergedTestComponent =
    MergedTestComponent::class.create()
```

No idea, why `KSTypeImpl` shows up, but it's clearly an internal KSP type. It should actually be the type of the argument of `ClassKey`, i.e. `KClass<*>` in this case, but other types e.g. `KClass<out CommonSuperType>` should also be supported.

**Comment by r0adkll** [comment]
Nice catch! Yah looks like I'm just directly passing through the first parameter argument of a map key annotation and missed accounting for `KClass` types. This should be an easy fix.
