### ISSUE TITLE
Name conflicts in kimchi.merge.hint

### ISSUE THREAD

**Issue by kodebach** [r0adkll/kimchi#53]
The files generated in `kimchi.merge.hint.merge` are not named in a way that prevents name conflicts.

Take this example

```kotlin
class Foo {
    @ContributesTo(AppScope::class)
    interface Dependencies {
         // ...
    }
}


class Bar {
    @ContributesTo(AppScope::class)
    interface Dependencies {
         // ...
    }
}
``` 

This will attempt to create the class `kimchi.merge.hint.merge.Dependencies` twice and lead to a `FileAlreadyExistsException`.

It seems the files in `kimchi.merge.hint.merge` are simply based on `simpleName`s and don't take package names or class nesting into account.

**Comment by kodebach** [comment]
A similar issue also happens, if the same class name is used in different packages.

**Comment by r0adkll** [comment]
Ah yup, should switch to using the fqname to ensure there are no collisions
